# Generated by Django 5.2.8 on 2025-11-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usuario',
        ),
    ]
